baseurl: "/"
title: "Phantom"
main_js: "assets/js/main.js"
params:
  none: ""
sass:
  input_file: sass/main.scss
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
#templates:
#  body_class: "is-preload"
